export interface QaKnowledgeRegressionCase {
  id: string
  prompt: string
  expectedDocTitle: string
  expectedTopHitKeywords: string[]
  expectedAnswerKeywords: string[]
  mustUseFetch: boolean
}

export const qaKnowledgeRegressionCases: QaKnowledgeRegressionCase[] = [
  {
    id: 'R01',
    prompt: '请基于《部署方案》回答：所有的介质和运行内容放在哪里？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['数据盘'],
    mustUseFetch: true,
  },
  {
    id: 'R02',
    prompt: '请基于《部署方案》回答：itsm-01 和 itsm-02 的操作系统是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['EulerOS 2 SP12 x86'],
    mustUseFetch: true,
  },
  {
    id: 'R03',
    prompt: '请基于《部署方案》回答：ops-agent 的操作系统和硬件配置是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['EulerOS 2 SP12 x86', '16C', '64G', '50G', '2T'],
    mustUseFetch: true,
  },
  {
    id: 'R04',
    prompt: '请基于《部署方案》回答：llm-service-01 和 llm-service-02 的操作系统是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['Ubuntu 20.04 x86'],
    mustUseFetch: true,
  },
  {
    id: 'R05',
    prompt: '请基于《部署方案》回答：管理后台和部署后台分别是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['GKIT', 'GDE 26.1'],
    mustUseFetch: true,
  },
  {
    id: 'R06',
    prompt: '请基于《部署方案》回答：运维智能体网关对应的组件名和版本是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['运维智能体网关'],
    mustUseFetch: true,
  },
  {
    id: 'R07',
    prompt: '请基于《部署方案》回答：QA 模型和 Embedding 模型分别是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['QA', 'Embedding'],
    mustUseFetch: true,
  },
  {
    id: 'R08',
    prompt: '请基于《部署方案》回答：Universal 推理服务的 GPU 分配、TP 和 MaxLen 分别是什么？',
    expectedDocTitle: '部署方案',
    expectedTopHitKeywords: ['部署方案'],
    expectedAnswerKeywords: ['GPU', 'TP', 'MaxLen'],
    mustUseFetch: true,
  },
  {
    id: 'R09',
    prompt: '请基于《Major Incident Analysis Report》回答：事件编号是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['INC20250115001'],
    mustUseFetch: true,
  },
  {
    id: 'R10',
    prompt: '请基于《Major Incident Analysis Report》回答：这个事件的优先级、类别和状态分别是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['P1', 'Database', 'Resolved'],
    mustUseFetch: true,
  },
  {
    id: 'R11',
    prompt: '请基于《Major Incident Analysis Report》回答：事件的创建时间和解决时间分别是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['2025-01-15 09:15', '2025-01-15 12:45'],
    mustUseFetch: true,
  },
  {
    id: 'R12',
    prompt: '请基于《Major Incident Analysis Report》回答：事件持续了多久，Response Time SLA 和 Resolution Time SLA 分别是什么状态？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['3.5 hours', 'Met', 'Violated'],
    mustUseFetch: true,
  },
  {
    id: 'R13',
    prompt: '请基于《Major Incident Analysis Report》回答：受影响的系统有哪些？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['交易系统', '订单服务', '支付网关', '用户中心', '商户后台'],
    mustUseFetch: true,
  },
  {
    id: 'R14',
    prompt: '请基于《Major Incident Analysis Report》回答：09:15 的自动告警具体发现了什么异常？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['连接失败率 > 90%', '主节点无响应'],
    mustUseFetch: true,
  },
  {
    id: 'R15',
    prompt: '请基于《Major Incident Analysis Report》回答：09:16 工单被自动分配给了谁，他是什么角色？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['李明', 'L1 值班'],
    mustUseFetch: true,
  },
  {
    id: 'R16',
    prompt: '请基于《Major Incident Analysis Report》回答：09:25 为什么要从 L1 运维升级到 L2 DBA 团队？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['DBA 专家', '数据库故障切换'],
    mustUseFetch: true,
  },
  {
    id: 'R17',
    prompt: '请基于《Major Incident Analysis Report》回答：09:35 发现了什么数据同步问题？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['从节点数据同步延迟约 5 分钟'],
    mustUseFetch: true,
  },
  {
    id: 'R18',
    prompt: '请基于《Major Incident Analysis Report》回答：09:45 业务负责人依据什么业务影响做出了什么决定？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['每分钟损失约 50 万交易额', '决定接受切换风险'],
    mustUseFetch: true,
  },
  {
    id: 'R19',
    prompt: '请基于《Major Incident Analysis Report》回答：10:15 发现了大约多少笔交易数据不一致？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['约 2000 笔'],
    mustUseFetch: true,
  },
  {
    id: 'R20',
    prompt: '请基于《Major Incident Analysis Report》回答：10:20 数据恢复工作转交给了谁，目的是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['陈芳', '数据恢复专家', '交给专业人员处理'],
    mustUseFetch: true,
  },
  {
    id: 'R21',
    prompt: '请基于《Major Incident Analysis Report》回答：11:45 恢复正常的关键监控指标是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['交易成功率 99.9%', '响应时间正常'],
    mustUseFetch: true,
  },
  {
    id: 'R22',
    prompt: '请基于《Major Incident Analysis Report》回答：12:00 IDC 最终确认的故障点是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['磁盘阵列控制器故障'],
    mustUseFetch: true,
  },
  {
    id: 'R23',
    prompt: '请基于《Major Incident Analysis Report》回答：12:30 记录的最终故障根因是什么？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['磁盘阵列控制器硬件故障'],
    mustUseFetch: true,
  },
  {
    id: 'R24',
    prompt: '请基于《Major Incident Analysis Report》回答：12:45 关闭工单时确认了哪些事情？',
    expectedDocTitle: 'Major Incident Analysis Report',
    expectedTopHitKeywords: ['Major Incident Analysis Report'],
    expectedAnswerKeywords: ['业务完全恢复', '数据完整性验证通过'],
    mustUseFetch: true,
  },
  {
    id: 'R25',
    prompt: '请基于《SLA违约归因分析报告》回答：执行摘要里的总工单数、响应 SLA、解决 SLA 和高风险工单数分别是多少？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['8,977', '99.9%', '64.2%', '4,423'],
    mustUseFetch: true,
  },
  {
    id: 'R26',
    prompt: '请基于《SLA违约归因分析报告》回答：P1 的响应目标、解决目标、响应 SLA 和解决 SLA 分别是多少？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['15 min', '2 h', '98.9%', '6.9%'],
    mustUseFetch: true,
  },
  {
    id: 'R27',
    prompt: '请基于《SLA违约归因分析报告》回答：P2 的响应目标、解决目标、响应 SLA 和解决 SLA 分别是多少？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['30 min', '6 h', '99.7%', '15.5%'],
    mustUseFetch: true,
  },
  {
    id: 'R28',
    prompt: '请基于《SLA违约归因分析报告》回答：P4 的响应 SLA、解决 SLA 和总量分别是多少？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['100.0%', '99.7%', '4,042'],
    mustUseFetch: true,
  },
  {
    id: 'R29',
    prompt: '请基于《SLA违约归因分析报告》回答：占比最高的违约归因因素是什么，占比多少？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['时间窗', '44%'],
    mustUseFetch: true,
  },
  {
    id: 'R30',
    prompt: '请基于《SLA违约归因分析报告》回答：为什么归因总数和违约总数不一样？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['单个工单可能有多个归因因素'],
    mustUseFetch: true,
  },
  {
    id: 'R31',
    prompt: '请基于《SLA违约归因分析报告》回答：哪一个类别占了 1,480 个违约，占总数的多少？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['Digital View Monitoring', '46%'],
    mustUseFetch: true,
  },
  {
    id: 'R32',
    prompt: '请基于《SLA违约归因分析报告》回答：高风险工单 Top 10 里出现最多的类别是什么？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['Digital View Monitoring'],
    mustUseFetch: true,
  },
  {
    id: 'R33',
    prompt: '请基于《SLA违约归因分析报告》回答：流程改进部分给出的两条建议是什么？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['减少平均转派次数', '基于技能的路由'],
    mustUseFetch: true,
  },
  {
    id: 'R34',
    prompt: '请基于《SLA违约归因分析报告》回答：时间窗口因素部分给出的两条建议是什么？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['18:00-09:00', '周末轮值制度'],
    mustUseFetch: true,
  },
  {
    id: 'R35',
    prompt: '请基于《SLA违约归因分析报告》回答：外部依赖部分给出的两条建议是什么？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['SLA协议', '自动客户跟进提醒'],
    mustUseFetch: true,
  },
  {
    id: 'R36',
    prompt: '请基于《SLA违约归因分析报告》回答：P1/P2 SLA 表现部分给出的两条建议是什么？',
    expectedDocTitle: 'SLA违约归因分析报告',
    expectedTopHitKeywords: ['SLA违约归因分析报告'],
    expectedAnswerKeywords: ['专门的P1/P2响应团队', '50% SLA消耗后自动升级机制'],
    mustUseFetch: true,
  },
  {
    id: 'R37',
    prompt: '请基于《Comprehensive Quality Report》回答：Health Score 和 Incident SLA Rate 分别是多少，状态是什么？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'Health Score'],
    expectedAnswerKeywords: ['33', '64.2%', 'At Risk'],
    mustUseFetch: true,
  },
  {
    id: 'R38',
    prompt: '请基于《Comprehensive Quality Report》回答：Change Success Rate、Request Fulfillment 和 CSAT 分别是多少？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'Change Success Rate'],
    expectedAnswerKeywords: ['84.0%', '66.0%', '3.61'],
    mustUseFetch: true,
  },
  {
    id: 'R39',
    prompt: '请基于《Comprehensive Quality Report》回答：Problem Closure Rate 和 MTTR 分别是多少？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'Problem Closure Rate'],
    expectedAnswerKeywords: ['48.0%', '29.4h'],
    mustUseFetch: true,
  },
  {
    id: 'R40',
    prompt: '请基于《Comprehensive Quality Report》回答：Top Risks 里两个 Critical 风险分别是什么？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'Top Risks'],
    expectedAnswerKeywords: ['Incident SLA compliance at 64.2%', '9 changes caused incidents (18.0%)'],
    mustUseFetch: true,
  },
  {
    id: 'R41',
    prompt: '请基于《Comprehensive Quality Report》回答：AI Insight 最关键的一条改进建议是什么？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'AI Insight'],
    expectedAnswerKeywords: ['Major Incident Review', 'Problem Management process'],
    mustUseFetch: true,
  },
  {
    id: 'R42',
    prompt: '请基于《Comprehensive Quality Report》回答：报告预计下一个季度会带来什么影响？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'Expected Impact'],
    expectedAnswerKeywords: ['25%', 'next quarter', 'Service Health Score'],
    mustUseFetch: true,
  },
  {
    id: 'R43',
    prompt: '请基于《Comprehensive Quality Report》回答：文中给出的 Incidents 和 Problems 的比例大约是多少，这说明了什么？',
    expectedDocTitle: 'Comprehensive Quality Report',
    expectedTopHitKeywords: ['Executive Summary', 'Problems'],
    expectedAnswerKeywords: ['180:1', 'reactive', 'root cause'],
    mustUseFetch: true,
  },
  {
    id: 'R44',
    prompt: '请基于《Qwen3-32 模型服务性能测试结果（Agent场景）》回答：测试的 Base URL、模型名、Context sizes 和 Thinking mode 分别是什么？',
    expectedDocTitle: 'Qwen3-32 模型服务性能测试结果',
    expectedTopHitKeywords: ['Qwen3-32', 'Model Service Benchmark'],
    expectedAnswerKeywords: ['http://127.0.0.1:8000/v1', 'Qwen3-32B', '128,512,2048,4096,8192', 'no_think'],
    mustUseFetch: true,
  },
  {
    id: 'R45',
    prompt: '请基于《Qwen3-32 模型服务性能测试结果（Agent场景）》回答：Avg TTFT、Max TTFT 和 TPS 分别是多少？',
    expectedDocTitle: 'Qwen3-32 模型服务性能测试结果',
    expectedTopHitKeywords: ['Qwen3-32', 'Avg TTFT'],
    expectedAnswerKeywords: ['11.849', '15.649', '92.859'],
    mustUseFetch: true,
  },
  {
    id: 'R46',
    prompt: '请基于《AI’s trillion-dollar opportunity: Context graphs》回答：这篇文章的作者是谁，日期是什么时候？',
    expectedDocTitle: 'AI’s trillion-dollar opportunity: Context graphs',
    expectedTopHitKeywords: ['Context graphs', 'AI’s trillion-dollar opportunity'],
    expectedAnswerKeywords: ['Jaya Gupta', 'Ashu Garg', '2025 年 12 月 22 日'],
    mustUseFetch: true,
  },
  {
    id: 'R47',
    prompt: '请基于《AI’s trillion-dollar opportunity: Context graphs》回答：文中说企业真正缺失、但实际驱动企业运行的那一层是什么？',
    expectedDocTitle: 'AI’s trillion-dollar opportunity: Context graphs',
    expectedTopHitKeywords: ['Context graphs', 'decision traces'],
    expectedAnswerKeywords: ['decision traces', 'exceptions', 'overrides'],
    mustUseFetch: true,
  },
  {
    id: 'R48',
    prompt: '请基于《AI’s trillion-dollar opportunity: Context graphs》回答：rules 和 decision traces 的区别是什么？',
    expectedDocTitle: 'AI’s trillion-dollar opportunity: Context graphs',
    expectedTopHitKeywords: ['Context graphs', 'rules'],
    expectedAnswerKeywords: ['rules', 'decision traces', '过去如何应用规则'],
    mustUseFetch: true,
  },
  {
    id: 'R49',
    prompt: '请基于《智能化时代数据库自主可靠运维白皮书》回答：文中构建可靠运维服务体系提到的六个维度是什么？',
    expectedDocTitle: '智能化时代数据库自主可靠运维白皮书',
    expectedTopHitKeywords: ['智能化时代数据库自主可靠运维白皮书', '六大维度'],
    expectedAnswerKeywords: ['团队建设', '权责制度', '可观测体系', '标准化流程', '应急预案', '知识库沉淀'],
    mustUseFetch: true,
  },
  {
    id: 'R50',
    prompt: '请基于《智能化时代数据库自主可靠运维白皮书》回答：针对 RAG 召回率不足，文中建议引入哪两类技术或处理方式来提升召回准确率和稳定性？',
    expectedDocTitle: '智能化时代数据库自主可靠运维白皮书',
    expectedTopHitKeywords: ['智能化时代数据库自主可靠运维白皮书', 'RAG召回率不足'],
    expectedAnswerKeywords: ['知识图谱', 'GraphRAG', '多路召回'],
    mustUseFetch: true,
  },
]
